version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3333
    restart: unless-stopped